name: 'Mermaid'

on:
  push:
    paths:
      - '**/*.md'
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' | xargs)"

      - name: md files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action@0.3.1
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: '.resources'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
          OUTPUT_FILE_TYPE: "svg"

      - name: show changes
        run: |
          git status

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .resources/*.svg
          git commit -m "mermaid compiled" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.composer-run.outcome == 'success' && steps.composer-run.conclusion == 'success'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
